#
#                           Makefile 
#                   Do not edit this file 
#
#
#
include src_dir_path.mk
-include config.mk

SUBDIRS= \
data_util\
examples\

###########################################################################

all: $(SUBDIRS:%=%.all)
	@echo '************************************************'
	@echo '*'
	@echo '* FLL built successfully!'
	@echo '*'
	@echo '************************************************'

include rules.mk


init:
	echo PROJ_ROOT_PATH=$(PWD) > config.mk
	echo MAKEDEPEND=$(PWD)/python_dep/fort_depend.py >> config.mk

data_util.all: 
test.all: data_util.all

clean: $(SUBDIRS:%=%.clean)

depend: $(SUBDIRS:%=%.depend)

install: $(SUBDIRS:%=%.all) $(SUBDIRS:%=%.install)

test: $(SUBDIRS:%=%.test)

#
# The following target checks all .f90 files against
# some of the sourcecode standard rules.
#
CHK_SUBDIRS:=$(filter-out adaption lapack,$(SUBDIRS))
chk: $(CHK_SUBDIRS:%=%.chk)
#
#
.PHONY: path
