#
#                           Makefile 
#                   Do not edit this file 
#
#
#
include src_dir_path.mk
include config.mk

SUBDIRS= \
data_util\
test\

###########################################################################

all: $(SUBDIRS:%=%.all)
	@echo '************************************************'
	@echo '*'
	@echo '* FLL built successfully!'
	@MAKE=$(MAKE) && \
	 echo "* Type \"$${MAKE##*/} install\" to install FLL into directory $(bin_dir)"
	@echo "* "
	@MAKE=$(MAKE) && \
	 echo "*   $${MAKE##*/} bin_dir=/usr/local/bin"
	@echo '*'
	@echo '************************************************'

include rules.mk

data_util.all: 
test.all: data_util.all

clean: $(SUBDIRS:%=%.clean)

depend: $(SUBDIRS:%=%.depend)

install: $(SUBDIRS:%=%.all) $(SUBDIRS:%=%.install)

test: $(SUBDIRS:%=%.test)

#
# The following target checks all .f90 files against
# some of the sourcecode standard rules.
#
CHK_SUBDIRS:=$(filter-out adaption lapack,$(SUBDIRS))
chk: $(CHK_SUBDIRS:%=%.chk)
#
#
.PHONY: path
