!
!     Copyright (C) 2016  Adam Jirasek
! 
!     This program is free software: you can redistribute it and/or modify
!     it under the terms of the GNU Lesser General Public License as published by
!     the Free Software Foundation, either version 3 of the License, or
!     (at your option) any later version.
! 
!     This program is distributed in the hope that it will be useful,
!     but WITHOUT ANY WARRANTY; without even the implied warranty of
!     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!     GNU Lesser General Public License for more details.
! 
!     You should have received a copy of the GNU Lesser General Public License
!     along with this program.  If not, see <http://www.gnu.org/licenses/>.
!     
!     contact: libm3l@gmail.com
! 
!

!
!     FUNCTION FLL_GETNDATA
!
!     Date: 2016-10-10
! 
! 
!
!
!     Description: prints node
! 
!
!     Input parameters:
! 
!
!     Return value:
! 
! 
!
!     Modifications:
!     Date		Version		Patch number		CLA 
!
!
!     Description
!
!
MODULE FLL_GETNDATA_M
CONTAINS
!
!  SINGLE
!
  FUNCTION FLL_GETNDATA_R0(PNODE,NAME,NUMBER,LTYPE,FPAR) RESULT(R0)
   
    USE FLL_TYPE_M
    USE FLL_LOCATE_M
    
    IMPLICIT NONE
!
!   FUNCTION FIND NODES WITH SPECIFIED NAME 
!
   TYPE(FUNC_DATA_SET) :: FPAR
   TYPE(DNODE), POINTER  :: PNODE,PFIND
   CHARACTER(*) :: NAME
   CHARACTER(*) :: LTYPE
   INTEGER(LINT) :: NUMBER
   LOGICAL :: RECURSE
   REAL(RSINGLE) :: R0
!
!   LOCAL TYPES
!
   IF(.NOT.ASSOCIATED(PNODE))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A)')'FLL_GETNDATA_R0 - Null node '
      STOP
      RETURN      
   END IF

   PFIND => FLL_LOCATE(PNODE,NAME,NUMBER,LTYPE,.FALSE.,FPAR)

   IF(.NOT.ASSOCIATED(PFIND))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A,A,A)')'FLL_GETNDATA_R0 - Node',TRIM(PNODE%LNAME),' does not contain specified data'
      STOP
      RETURN
   END IF

   R0 = PNODE%R0
   RETURN

  END FUNCTION FLL_GETNDATA_R0



  FUNCTION FLL_GETNDATA_R1(PNODE,NAME,NUMBER,LTYPE,FPAR) RESULT(R1)
   
    USE FLL_TYPE_M
    USE FLL_LOCATE_M
    
    IMPLICIT NONE
!
!   FUNCTION FIND NODES WITH SPECIFIED NAME 
!
   TYPE(FUNC_DATA_SET) :: FPAR
   TYPE(DNODE), POINTER  :: PNODE,PFIND
   CHARACTER(*) :: NAME
   CHARACTER(*) :: LTYPE
   INTEGER(LINT) :: NUMBER
   LOGICAL :: RECURSE
   REAL(RSINGLE), POINTER :: R1(:)
!
!   LOCAL TYPES
!
   IF(.NOT.ASSOCIATED(PNODE))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A)')'FLL_GETNDATA_R1 - Null node '
      STOP
      RETURN      
   END IF

   PFIND => FLL_LOCATE(PNODE,NAME,NUMBER,LTYPE,.FALSE.,FPAR)

   IF(.NOT.ASSOCIATED(PFIND))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A,A,A)')'FLL_GETNDATA_R1 - Node',TRIM(PNODE%LNAME),' does not contain specified data'
      STOP
      RETURN
   END IF

   R1 => PFIND%R1
   RETURN

  END FUNCTION FLL_GETNDATA_R1

  FUNCTION FLL_GETNDATA_R2(PNODE,NAME,NUMBER,LTYPE,FPAR) RESULT(R2)
   
    USE FLL_TYPE_M
    USE FLL_LOCATE_M
    
    IMPLICIT NONE
!
!   FUNCTION FIND NODES WITH SPECIFIED NAME 
!
   TYPE(FUNC_DATA_SET) :: FPAR
   TYPE(DNODE), POINTER  :: PNODE,PFIND
   CHARACTER(*) :: NAME
   CHARACTER(*) :: LTYPE
   INTEGER(LINT) :: NUMBER
   LOGICAL :: RECURSE
   REAL(RSINGLE), POINTER :: R2(:,:)
!
!   LOCAL TYPES
!
   IF(.NOT.ASSOCIATED(PNODE))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A)')'FLL_GETNDATA_R2 - Null node '
      STOP
      RETURN      
   END IF

   PFIND => FLL_LOCATE(PNODE,NAME,NUMBER,LTYPE,.FALSE.,FPAR)

   IF(.NOT.ASSOCIATED(PFIND))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A,A,A)')'FLL_GETNDATA_R2 - Node',TRIM(PNODE%LNAME),' does not contain specified data'
      STOP
      RETURN
   END IF

   R2 => PFIND%R2
   RETURN

  END FUNCTION FLL_GETNDATA_R2
!
!  DOUBLE
!
  FUNCTION FLL_GETNDATA_D0(PNODE,NAME,NUMBER,LTYPE,FPAR) RESULT(R0)
   
    USE FLL_TYPE_M
    USE FLL_LOCATE_M
    
    IMPLICIT NONE
!
!   FUNCTION FIND NODES WITH SPECIFIED NAME 
!
   TYPE(FUNC_DATA_SET) :: FPAR
   TYPE(DNODE), POINTER  :: PNODE,PFIND
   CHARACTER(*) :: NAME
   CHARACTER(*) :: LTYPE
   INTEGER(LINT) :: NUMBER
   LOGICAL :: RECURSE
   REAL(RDOUBLE) :: R0
!
!   LOCAL TYPES
!
   IF(.NOT.ASSOCIATED(PNODE))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A)')'FLL_GETNDATA_D0 - Null node '
      STOP
      RETURN      
   END IF

   PFIND => FLL_LOCATE(PNODE,NAME,NUMBER,LTYPE,.FALSE.,FPAR)

   IF(.NOT.ASSOCIATED(PFIND))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A,A,A)')'FLL_GETNDATA_D0 - Node',TRIM(PNODE%LNAME),' does not contain specified data'
      STOP
      RETURN
   END IF

   R0 = PNODE%D0
   RETURN

  END FUNCTION FLL_GETNDATA_D0



  FUNCTION FLL_GETNDATA_D1(PNODE,NAME,NUMBER,LTYPE,FPAR) RESULT(R1)
   
    USE FLL_TYPE_M
    USE FLL_LOCATE_M
    
    IMPLICIT NONE
!
!   FUNCTION FIND NODES WITH SPECIFIED NAME 
!
   TYPE(FUNC_DATA_SET) :: FPAR
   TYPE(DNODE), POINTER  :: PNODE,PFIND
   CHARACTER(*) :: NAME
   CHARACTER(*) :: LTYPE
   INTEGER(LINT) :: NUMBER
   LOGICAL :: RECURSE
   REAL(RDOUBLE), POINTER :: R1(:)
!
!   LOCAL TYPES
!
   IF(.NOT.ASSOCIATED(PNODE))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A)')'FLL_GETNDATA_D1 - Null node '
      STOP
      RETURN      
   END IF

   PFIND => FLL_LOCATE(PNODE,NAME,NUMBER,LTYPE,.FALSE.,FPAR)

   IF(.NOT.ASSOCIATED(PFIND))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A,A,A)')'FLL_GETNDATA_D1 - Node',TRIM(PNODE%LNAME),' does not contain specified data'
      STOP
      RETURN
   END IF

   R1 => PFIND%D1
   
   RETURN

  END FUNCTION FLL_GETNDATA_D1

  FUNCTION FLL_GETNDATA_D2(PNODE,NAME,NUMBER,LTYPE,FPAR) RESULT(R2)
   
    USE FLL_TYPE_M
    USE FLL_LOCATE_M
    
    IMPLICIT NONE
!
!   FUNCTION FIND NODES WITH SPECIFIED NAME 
!
   TYPE(FUNC_DATA_SET) :: FPAR
   TYPE(DNODE), POINTER  :: PNODE,PFIND
   CHARACTER(*) :: NAME
   CHARACTER(*) :: LTYPE
   INTEGER(LINT) :: NUMBER
   LOGICAL :: RECURSE
   REAL(RDOUBLE), POINTER :: R2(:,:)
!
!   LOCAL TYPES
!
   IF(.NOT.ASSOCIATED(PNODE))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A)')'FLL_GETNDATA_D2 - Null node '
      STOP
      RETURN      
   END IF

   PFIND => FLL_LOCATE(PNODE,NAME,NUMBER,LTYPE,.FALSE.,FPAR)

   IF(.NOT.ASSOCIATED(PFIND))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A,A,A)')'FLL_GETNDATA_D2 - Node',TRIM(PNODE%LNAME),' does not contain specified data'
      STOP
      RETURN
   END IF

   R2 => PFIND%D2
   RETURN

  END FUNCTION FLL_GETNDATA_D2
!
!  INTEGER
!
  FUNCTION FLL_GETNDATA_I0(PNODE,NAME,NUMBER,LTYPE,FPAR) RESULT(I0)
   
    USE FLL_TYPE_M
    USE FLL_LOCATE_M
    
    IMPLICIT NONE
!
!   FUNCTION FIND NODES WITH SPECIFIED NAME 
!
   TYPE(FUNC_DATA_SET) :: FPAR
   TYPE(DNODE), POINTER  :: PNODE,PFIND
   CHARACTER(*) :: NAME
   CHARACTER(*) :: LTYPE
   INTEGER(LINT) :: NUMBER
   LOGICAL :: RECURSE
   INTEGER(SINT) :: I0
!
!   LOCAL TYPES
!
   IF(.NOT.ASSOCIATED(PNODE))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A)')'FLL_GETNDATA_I0 - Null node '
      STOP
      RETURN      
   END IF

   PFIND => FLL_LOCATE(PNODE,NAME,NUMBER,LTYPE,.FALSE.,FPAR)

   IF(.NOT.ASSOCIATED(PFIND))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A,A,A)')'FLL_GETNDATA_I0 - Node',TRIM(PNODE%LNAME),' does not contain specified data'
      STOP
      RETURN
   END IF

   I0 = PNODE%I0
   RETURN

  END FUNCTION FLL_GETNDATA_I0



  FUNCTION FLL_GETNDATA_I1(PNODE,NAME,NUMBER,LTYPE,FPAR) RESULT(I1)
   
    USE FLL_TYPE_M
    USE FLL_LOCATE_M
    
    IMPLICIT NONE
!
!   FUNCTION FIND NODES WITH SPECIFIED NAME 
!
   TYPE(FUNC_DATA_SET) :: FPAR
   TYPE(DNODE), POINTER  :: PNODE,PFIND
   CHARACTER(*) :: NAME
   CHARACTER(*) :: LTYPE
   INTEGER(LINT) :: NUMBER
   LOGICAL :: RECURSE
   INTEGER(SINT), POINTER :: I1(:)
!
!   LOCAL TYPES
!
   IF(.NOT.ASSOCIATED(PNODE))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A)')'FLL_GETNDATA_I1 - Null node '
      STOP
      RETURN      
   END IF

   PFIND => FLL_LOCATE(PNODE,NAME,NUMBER,LTYPE,.FALSE.,FPAR)

   IF(.NOT.ASSOCIATED(PFIND))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A,A,A)')'FLL_GETNDATA_I1 - Node',TRIM(PNODE%LNAME),' does not contain specified data'
      STOP
      RETURN
   END IF

   I1 => PFIND%I1
   RETURN

  END FUNCTION FLL_GETNDATA_I1

  FUNCTION FLL_GETNDATA_I2(PNODE,NAME,NUMBER,LTYPE,FPAR) RESULT(I2)
   
    USE FLL_TYPE_M
    USE FLL_LOCATE_M
    
    IMPLICIT NONE
!
!   FUNCTION FIND NODES WITH SPECIFIED NAME 
!
   TYPE(FUNC_DATA_SET) :: FPAR
   TYPE(DNODE), POINTER  :: PNODE,PFIND
   CHARACTER(*) :: NAME
   CHARACTER(*) :: LTYPE
   INTEGER(LINT) :: NUMBER
   LOGICAL :: RECURSE
   INTEGER(SINT), POINTER :: I2(:,:)
!
!   LOCAL TYPES
!
   IF(.NOT.ASSOCIATED(PNODE))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A)')'FLL_GETNDATA_I2 - Null node '
      STOP
      RETURN      
   END IF

   PFIND => FLL_LOCATE(PNODE,NAME,NUMBER,LTYPE,.FALSE.,FPAR)

   IF(.NOT.ASSOCIATED(PFIND))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A,A,A)')'FLL_GETNDATA_I2 - Node',TRIM(PNODE%LNAME),' does not contain specified data'
      STOP
      RETURN
   END IF

   I2 => PFIND%I2
   RETURN

  END FUNCTION FLL_GETNDATA_I2
!
!  LONG INTEGER
!
  FUNCTION FLL_GETNDATA_L0(PNODE,NAME,NUMBER,LTYPE,FPAR) RESULT(I0)
   
    USE FLL_TYPE_M
    USE FLL_LOCATE_M
    
    IMPLICIT NONE
!
!   FUNCTION FIND NODES WITH SPECIFIED NAME 
!
   TYPE(FUNC_DATA_SET) :: FPAR
   TYPE(DNODE), POINTER  :: PNODE,PFIND
   CHARACTER(*) :: NAME
   CHARACTER(*) :: LTYPE
   INTEGER(LINT) :: NUMBER
   LOGICAL :: RECURSE
   INTEGER(LINT) :: I0
!
!   LOCAL TYPES
!
   IF(.NOT.ASSOCIATED(PNODE))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A)')'FLL_GETNDATA_L0 - Null node '
      STOP
      RETURN      
   END IF

   PFIND => FLL_LOCATE(PNODE,NAME,NUMBER,LTYPE,.FALSE.,FPAR)

   IF(.NOT.ASSOCIATED(PFIND))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A,A,A)')'FLL_GETNDATA_L0 - Node',TRIM(PNODE%LNAME),' does not contain specified data'
      STOP
      RETURN
   END IF

   I0 = PNODE%L0
   RETURN

  END FUNCTION FLL_GETNDATA_L0



  FUNCTION FLL_GETNDATA_L1(PNODE,NAME,NUMBER,LTYPE,FPAR) RESULT(I1)
   
    USE FLL_TYPE_M
    USE FLL_LOCATE_M
    
    IMPLICIT NONE
!
!   FUNCTION FIND NODES WITH SPECIFIED NAME 
!
   TYPE(FUNC_DATA_SET) :: FPAR
   TYPE(DNODE), POINTER  :: PNODE,PFIND
   CHARACTER(*) :: NAME
   CHARACTER(*) :: LTYPE
   INTEGER(LINT) :: NUMBER
   LOGICAL :: RECURSE
   INTEGER(LINT), POINTER :: I1(:)
!
!   LOCAL TYPES
!
   IF(.NOT.ASSOCIATED(PNODE))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A)')'FLL_GETNDATA_L1 - Null node '
      STOP
      RETURN      
   END IF

   PFIND => FLL_LOCATE(PNODE,NAME,NUMBER,LTYPE,.FALSE.,FPAR)

   IF(.NOT.ASSOCIATED(PFIND))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A,A,A)')'FLL_GETNDATA_L1 - Node',TRIM(PNODE%LNAME),' does not contain specified data'
      STOP
      RETURN
   END IF

   I1 => PFIND%L1
   RETURN

  END FUNCTION FLL_GETNDATA_L1

  FUNCTION FLL_GETNDATA_L2(PNODE,NAME,NUMBER,LTYPE,FPAR) RESULT(I2)
   
    USE FLL_TYPE_M
    USE FLL_LOCATE_M
    
    IMPLICIT NONE
!
!   FUNCTION FIND NODES WITH SPECIFIED NAME 
!
   TYPE(FUNC_DATA_SET) :: FPAR
   TYPE(DNODE), POINTER  :: PNODE,PFIND
   CHARACTER(*) :: NAME
   CHARACTER(*) :: LTYPE
   INTEGER(LINT) :: NUMBER
   LOGICAL :: RECURSE
   INTEGER(LINT), POINTER :: I2(:,:)
!
!   LOCAL TYPES
!
   IF(.NOT.ASSOCIATED(PNODE))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A)')'FLL_GETNDATA_L2 - Null node '
      STOP
      RETURN      
   END IF

   PFIND => FLL_LOCATE(PNODE,NAME,NUMBER,LTYPE,.FALSE.,FPAR)

   IF(.NOT.ASSOCIATED(PFIND))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A,A,A)')'FLL_GETNDATA_L2 - Node',TRIM(PNODE%LNAME),' does not contain specified data'
      STOP
      RETURN
   END IF

   I2 => PFIND%L2
   RETURN

  END FUNCTION FLL_GETNDATA_L2
  
  
  
  
    FUNCTION FLL_GETNDATA_S(PNODE,NAME,NUMBER,LTYPE,FPAR) RESULT(STRING)
   
    USE FLL_TYPE_M
    USE FLL_LOCATE_M
    
    IMPLICIT NONE
!
!   FUNCTION FIND NODES WITH SPECIFIED NAME 
!
   TYPE(FUNC_DATA_SET) :: FPAR
   TYPE(DNODE), POINTER  :: PNODE,PFIND
   CHARACTER(*) :: NAME
   CHARACTER(*) :: LTYPE
   INTEGER(LINT) :: NUMBER
   LOGICAL :: RECURSE
   CHARACTER(LEN=STRING_LENGHT) :: STRING
!
!   LOCAL TYPES
!
   IF(.NOT.ASSOCIATED(PNODE))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A)')'FLL_GETNDATA_L0 - Null node '
      STOP
      RETURN      
   END IF

   PFIND => FLL_LOCATE(PNODE,NAME,NUMBER,LTYPE,.FALSE.,FPAR)

   IF(.NOT.ASSOCIATED(PFIND))THEN
      FPAR%SUCCESS = .FALSE.
      WRITE(FPAR%MESG,'(A,A,A)')'FLL_GETNDATA_L0 - Node',TRIM(PNODE%LNAME),' does not contain specified data'
      STOP
      RETURN
   END IF

   STRING = PNODE%S
   RETURN

  END FUNCTION FLL_GETNDATA_S

END MODULE FLL_GETNDATA_M
